---
- name: List all Softwares on Windows Server
  hosts: 192.168.1.44
  vars:
    uuids: |
      {%- set o=[] %}
      {%- for i in play_hosts %}
        {%- if o.append(hostvars[i].uuid) %}
        {%- endif %}
      {%- endfor %}
      {{ o }}

  tasks:
  - name: List all x64 software names into the software variable in dictionary form
    ansible.builtin.win_shell: |
               Get-ItemProperty HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\* | Select-Object DisplayName
    register: software
    
  - name: List all x64 software versions into the softwareversion variable in dictionary form
    ansible.builtin.win_shell: |
               Get-ItemProperty HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\* | Select-Object DisplayVersion
    register: softwareversion

  - name: List all 32bit software names into the software variable in dictionary form
    ansible.builtin.win_shell: |
               Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* | Select-Object DisplayName
    register: softwarenames

  - name: List all 32bit software versions into the software variable in dictionary form
    ansible.builtin.win_shell: |
               Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* | Select-Object DisplayVersion
    register: softwareversion2

  - name: Initialize empty lists to store software names, host ip, and versions
    set_fact:
      snames: []
      shost: []
      sversions: []

  - name: add names and host ip of x64 softwares
    with_items: "{{ software.stdout_lines }}"
    set_fact:
      snames: "{{ snames + [ item ] | select() }}"

  - name: add names and host ip of 32 bit softwares
    with_items: "{{ softwarenames.stdout_lines }}"
    set_fact:
      snames: "{{ snames + [ item ] | select() }}"

  - name: add versions of x64 softwares
    with_items: "{{ softwareversion.stdout_lines }}"
    set_fact:
      sversions: "{{ sversions + [ item ] | select() }}"

  - name: add versions of 32 bit softwares
    with_items: "{{ softwareversion2.stdout_lines }}"
    set_fact:
      sversions: "{{ sversions + [ item ] | select() }}"

  - name: remove empty values from lists
    set_fact:
      snamesfinal: "{{ snames | select() | list }}"
      sversionsfinal: "{{ sversions | select() | list }}"

  - name: add host ip for each softwarename
    with_items: "{{ snamesfinal }}"
    set_fact:
      snames: "{{ snames + [ item ] }}"
      shost: "{{ shost + [ ansible_ssh_host ] }}"

  - name: combine data from all windows host
    set_fact:
        uuid: "{{ shost | zip(snamesfinal) | map('join', ', ') | zip(sversionsfinal) | map('join', ', ') | join('\n') }}"

  - name: write list of softwares into a variable
    add_host:
        name: "192.168.1.41"
        VAR2_NEW: "{{ uuids | join(', ') }}"

- name: Store windowss list of software on the control server
  hosts: 192.168.1.41

  tasks:
  - name: copy windows software list to csv file WindowsSoftwareList.csv
    copy:
      content: "{{ hostvars['192.168.1.41']['VAR2_NEW'] }}"
      dest: "WindowsSoftwareList.csv"

  - debug:
        msg: "List of all programs on the host has been created in the home directory."
